 const authRoute = require("./auth.routes");
 const placeRoute = require("./place.routes");
 const categoryRoute = require("./category.routes");
 const extraRoute = require("./extra.routes");
 const productRoute = require("./product.routes");
 const reviewRoute = require("./review.routes");
 const favoriteRoute = require("./favorite.routes");
 const orderRoute = require("./order.routes");
 module.exports ={authRoute,placeRoute,categoryRoute,extraRoute,productRoute,reviewRoute,favoriteRoute,orderRoute}